name: GitHub Pages

on:
  push:
    branches:
    - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
    - name: Git Config
      run: |
        git config --global user.email "marklowelmontealto14@gmail.com"
        git config --global user.name "KuyaGit"
    
    - name: Delete existing files in prod branch
      run: |
        git clone --single-branch --branch prod https://github.com/${{ github.repository }} temp-prod
        cd temp-prod
        git rm -rf .
        git commit -m "Remove existing files and folders"
        git push origin prod
      if: success()

    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist # Change this to your build directory
        enable_jekyll: true
        publish_branch: prod
